export class BuyCoffee {
  static buy_coffee_link_texts = [
    "Jeśli chcesz, by moje życie nie polegało wyłącznie na wirtualnych kebabach, wesprzyj mnie.",
    "Aby uratować kebaba, niezbędne jest wsparcie w tej cyfrowej galaktyce. Kup mi jednego!",
    "Gdyby moje podniebienie było bardziej technologiczne, kebab byłby moim procesorem. Pomóż mi go kupić.",
    "Dzięki Twojemu wsparciu, komputer nie będzie musiał jeść kebaba zamiast mnie.",
    "Wirtualne kebaby są smaczne, ale rzeczywiste – jeszcze smaczniejsze. Pomóż mi je zdobyć.",
    "Wsparcie finansowe na kebaba – bo każdemu twórcy należy się posiłek, nie tylko kod.",
    "Kiedyś programiści jedli kebaby z kebaba, ale teraz muszą je prosić o wsparcie. Tak to już jest.",
    "Dzięki Twojemu wsparciu poczuję się jak kebab na talerzu – pełny i szczęśliwy.",
    "Kiedyś kebab to była tylko tradycja. Teraz to misja. Pomóż mi ją zrealizować.",
    "Chciałem stworzyć coś wielkiego, ale najpierw muszę zjeść kebaba. Wspieraj mnie!",
    "Jeśli chceš, by mój kod był smaczniejszy, wesprzyj mnie na kebaba. Pyszne błędy to moja specjalność.",
    "Bez Twojego wsparcia nie będę mógł napisać kolejnej linijki kodu – bez kebaba nie ma mocy!",
    "Ratuj kebabową misję – każda kawa to krok ku pełnemu talerzowi.",
    "Twój kebabowy wkład w moją pracę to inwestycja w lepszy kod i lepszy smak.",
    "Gdyby nie kebab, komputer by nie działał. Pomóż mi nie zwariować na pusty żołądek.",
    "Połączenie kebaba i kodu to sekretny algorytm sukcesu. Pomóż mi go zrealizować.",
    "Bez wsparcia nie zjem kebaba, a wtedy kodowanie stanie się niemożliwe.",
    "Każdy kebab to mniejsza szansa na awarię. Wspieraj mnie, zanim cały system się zawali.",
    "Kiedy kod działa, ale brakuje kebaba, nie ma sensu w tej wirtualnej rzeczywistości.",
    "Kiedy masz kod do napisania, ale kebab wciąż czeka. Pomóż mi rozwiązać tę zagadkę!",
    "W bezkresie internetu, gdzie kebab jest tylko marzeniem, Twoje wsparcie może je spełnić.",
    "Moje procesory działają, ale brakuje mi kebaba. Pomóż mi nakarmić moje wirtualne ja.",
    "Zanim stworzę coś niezwykłego, muszę najeść się kebaba. Pomożesz?",
    "Kiedy kod staje się ciężki, a żołądek pusty – kebab to jedyna odpowiedź.",
    "Zanim świat stanie się lepszy, najpierw muszę zjeść kebaba. Wspieraj mnie!",
    "W kodzie nie ma miejsca na przerwy, ale kebab to jedyny wyjątek. Pomóż mi na niego!",
    "Potrzebuję wsparcia, by nie zginąć w wirze kebabowej ekstazy. Pomóż mi nie stracić sensu!",
    "Bez kawałka kebaba, moja kreatywność już nie działa. Wspieraj, by nie zwariować.",
    "Gdy komputer przestaje jeść, ja szukam kebaba. Pomóż mi połączyć te dwa światy!",
    "Chciałbym stworzyć program, który sam sobie zamówi kebaba. Póki co, czekam na wsparcie.",
    "Kiedy kebab staje się celem, a kod tylko narzędziem. Wspieraj moją misję.",
    "Jeśli moje kody będą pełne kebaba, staną się bardziej smaczne. Wspieraj ten projekt!"
  ];
  static buy_coffe_link = 'buycoffee.to/futsal';
}